#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/qjs /etc/podkop/main.js
    procd_set_param respawn
    procd_close_instance
}

EXTRA_COMMANDS="list_update add_route_interface"
EXTRA_HELP="        list_update     Updating domain and subnet lists
        add_route_interface  Adding route for interface"

list_update() {
    /usr/bin/qjs /etc/podkop/main.js --update-lists
}

add_route_interface() {
    /usr/bin/qjs /etc/podkop/main.js --add-route "$1" "$2"
}