include $(TOPDIR)/rules.mk

PKG_NAME:=luci-i18n-podkop-ru
PKG_VERSION:=$(PKG_VERSION)

PKG_LICENSE:=MIT
PKG_MAINTAINER:=Ivan K <vizzlef@gmail.com>

LUCI_TITLE:=LuCI Podkop application Russian translation
LUCI_DEPENDS:=+luci-app-podkop
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature