name: Build packages

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build podkop and luci-app-podkop
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.1

      - name: Build and push
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          tags: podkop:ci

      - name: Create Docker container
        run: docker create --name podkop podkop:ci

      - name: Copy file from Docker container
        run: |
          docker cp podkop:/builder/bin/packages/x86_64/utilites/. ./bin/
          docker cp podkop:/builder/bin/packages/x86_64/luci/. ./bin/

      - name: Remove Docker container
        run: docker rm podkop

      - name: Release
        uses: softprops/action-gh-release@v2.0.8
        with:
          files: ./bin/*.ipk